# dbt project for Kinetic Intelligence Supply Chain
# Semantic layer, feature preparation

name: kinetic_isc
version: '0.1.0'
config-version: 2

profile: kinetic

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kinetic_isc:
    +materialized: view
