kinetic:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: kinetic
      password: kinetic
      dbname: kinetic
      schema: public
      threads: 4
